# Generated by Django 5.0 on 2024-01-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('customer_address', models.TextField()),
                ('company_name', models.CharField(max_length=200)),
                ('warranty_duration', models.IntegerField()),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(max_length=50)),
            ],
        ),
    ]
