# Generated by Django 5.0.1 on 2024-01-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
