# Generated by Django 5.0.1 on 2024-01-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
