# Generated by Django 5.0.1 on 2024-01-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
