# Generated by Django 5.0.1 on 2024-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOtp',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('otp', models.PositiveIntegerField()),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
