# Generated by Django 5.0.1 on 2024-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customerotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerotp',
            name='expiry_time',
        ),
        migrations.AddField(
            model_name='customerotp',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
