# Generated by Django 5.0.1 on 2024-02-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_customerotp_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='/static/images/default_images/default_dp.jpeg', upload_to='customer_pics/'),
        ),
    ]
