# Generated by Django 5.0 on 2024-01-12 03:55

import django.db.models.deletion
import ipcs_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.CharField(default=ipcs_admin.models.repair_unique_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('address_customer', models.TextField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('item_description', models.CharField(max_length=200)),
                ('error_raised', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.CharField(default=ipcs_admin.models.service_unique_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('application_datetime', models.DateTimeField(auto_now_add=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_site', models.TextField()),
                ('item_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('prefered_date', models.DateField()),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('service_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('residential_location', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedWarrantyApplication',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('approved_datetime', models.DateTimeField(auto_now_add=True)),
                ('application_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=150)),
                ('purchase_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(max_length=50)),
                ('product_complain', models.TextField()),
                ('expiry_date', models.DateField()),
                ('feedback', models.TextField(blank=True, default='On progress !', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledService',
            fields=[
                ('id', models.CharField(editable=False, max_length=13, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ipcs_admin.servicerequest')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.technician')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.CharField(default=ipcs_admin.models.warranty_unique_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyApplication',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('purchase_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('product_complain', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
    ]
