# Generated by Django 5.0 on 2024-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0002_alter_technician_residential_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
