# Generated by Django 5.0 on 2024-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0003_alter_warranty_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
