# Generated by Django 5.0 on 2024-01-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0004_alter_servicerequest_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledservice',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='scheduledservice',
            name='technician',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.DeleteModel(
            name='ScheduledService',
        ),
    ]
