# Generated by Django 5.0 on 2024-01-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0006_servicerequest_scheduledservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
