# Generated by Django 5.0 on 2024-01-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0008_completedservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledservice',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.servicerequest'),
        ),
    ]
