# Generated by Django 5.0 on 2024-01-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0009_alter_scheduledservice_service_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedservice',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.servicerequest'),
        ),
    ]
