# Generated by Django 5.0 on 2024-01-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0010_alter_completedservice_service_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedService',
        ),
    ]
