# Generated by Django 5.0 on 2024-01-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0011_delete_completedservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedService',
            fields=[
                ('id', models.CharField(editable=False, max_length=13, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('application_datetime', models.DateTimeField(auto_now_add=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_site', models.TextField()),
                ('item_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('prefered_date', models.DateField()),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('bussiness_name', models.CharField(max_length=150)),
                ('service_description', models.CharField(max_length=250)),
                ('service_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.technician')),
            ],
        ),
    ]
