# Generated by Django 5.0 on 2024-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0019_completedrepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedrepair',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='completedservice',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
