# Generated by Django 5.0 on 2024-01-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0020_alter_completedrepair_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedWarranty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('approved_datetime', models.DateTimeField(auto_now_add=True)),
                ('application_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=150)),
                ('purchase_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(max_length=50)),
                ('product_complain', models.TextField()),
                ('expiry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
    ]
