# Generated by Django 5.0.1 on 2024-01-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0021_claimedwarranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedrepair',
            name='error_raised',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='error_raised',
        ),
    ]
