# Generated by Django 5.0.1 on 2024-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0022_remove_completedrepair_error_raised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyapplication',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyapplication',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
