# Generated by Django 5.0.1 on 2024-01-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0023_alter_warrantyapplication_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimedWarranty',
        ),
    ]
