# Generated by Django 5.0.1 on 2024-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0027_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/images/default_images/no_image.jpeg', upload_to='product_images/'),
        ),
    ]
