# Generated by Django 5.0.1 on 2024-01-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0028_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(default='http://example.com', max_length=250),
        ),
    ]
