# Generated by Django 5.0.1 on 2024-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0029_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='client_images/'),
        ),
    ]
