# Generated by Django 5.0.1 on 2024-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0031_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default_images/no_image.jpeg', upload_to='product_images/'),
        ),
    ]
