# Generated by Django 5.0.1 on 2024-02-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0035_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
