# Generated by Django 5.0.1 on 2024-02-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0038_servicerequest_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='prefered_date',
        ),
    ]
