# Generated by Django 5.0.1 on 2024-02-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0039_remove_servicerequest_prefered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedrepair',
            old_name='item_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='repairrequest',
            old_name='item_name',
            new_name='product',
        ),
    ]
