# Generated by Django 5.0.1 on 2024-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0040_rename_item_name_completedrepair_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyapplication',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
