# Generated by Django 5.0.1 on 2024-02-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0042_repairrequest_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedwarrantyapplication',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimedwarranty',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
