# Generated by Django 5.0.1 on 2024-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0043_approvedwarrantyapplication_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedwarrantyapplication',
            name='feedback',
            field=models.TextField(blank=True, default='Not started.', null=True),
        ),
    ]
