# Generated by Django 5.0.1 on 2024-02-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0045_remove_scheduledrepair_ending_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledRepair',
            new_name='StartedRepairs',
        ),
    ]
