# Generated by Django 5.0.1 on 2024-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0046_rename_scheduledrepair_startedrepairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='startedrepairs',
            name='started_datetime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
