# Generated by Django 5.0.1 on 2024-02-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0047_startedrepairs_started_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartedRepairs',
            new_name='StartedRepair',
        ),
    ]
