# Generated by Django 5.0.1 on 2024-02-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0051_completedrepair_repairrequest_startedrepair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedservice',
            name='bussiness_name',
        ),
        migrations.RemoveField(
            model_name='completedservice',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='completedservice',
            name='prefered_date',
        ),
        migrations.RemoveField(
            model_name='completedservice',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='completedservice',
            name='starting_time',
        ),
        migrations.RemoveField(
            model_name='completedservice',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='bussiness_name',
        ),
    ]
