# Generated by Django 5.0.1 on 2024-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0052_remove_completedservice_bussiness_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
