# Generated by Django 5.0.1 on 2024-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0053_alter_servicerequest_model_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartedService',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('application_datetime', models.DateTimeField()),
                ('started_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('address_customer', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('product', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('service_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='completedservice',
            old_name='item_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='item_name',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_description',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ScheduledService',
        ),
    ]
