# Generated by Django 5.0.1 on 2024-02-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0054_startedservice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedService',
        ),
    ]
