# Generated by Django 5.0.1 on 2024-02-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0056_completedservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startedservice',
            old_name='address_customer',
            new_name='address_site',
        ),
    ]
