# Generated by Django 5.0.1 on 2024-02-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0060_servicereadytodispatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimedWarranty',
            new_name='FinishedWarranty',
        ),
    ]
