# Generated by Django 5.0.1 on 2024-02-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0061_rename_claimedwarranty_finishedwarranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedwarrantyapplication',
            old_name='application_date',
            new_name='application_datetime',
        ),
        migrations.RenameField(
            model_name='warrantyapplication',
            old_name='application_date',
            new_name='application_datetime',
        ),
        migrations.DeleteModel(
            name='FinishedWarranty',
        ),
    ]
