# Generated by Django 5.0.1 on 2024-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0065_alter_warrantyapplication_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedwarranty',
            name='finished_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
