# Generated by Django 5.0.1 on 2024-02-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0067_rename_approvedwarrantyapplication_acceptedwarrantyapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedwarrantyapplication',
            old_name='approved_datetime',
            new_name='accepted_datetime',
        ),
        migrations.RenameField(
            model_name='finishedwarranty',
            old_name='approved_datetime',
            new_name='accepted_datetime',
        ),
    ]
