# Generated by Django 5.0.1 on 2024-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0069_rejectedwarranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedwarranty',
            old_name='finished_datetime',
            new_name='rejected_datetime',
        ),
    ]
