# Generated by Django 5.0.1 on 2024-02-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0070_rename_finished_datetime_rejectedwarranty_rejected_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedwarranty',
            name='reason',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
