# Generated by Django 5.0.1 on 2024-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0071_rejectedwarranty_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedwarranty',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
