# Generated by Django 5.0.1 on 2024-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0072_finishedwarranty_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default_images/no_image.jpeg', null=True, upload_to='product_images/'),
        ),
    ]
