# Generated by Django 5.0.1 on 2024-02-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0076_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereadytodispatch',
            name='item_description',
        ),
        migrations.AddField(
            model_name='servicereadytodispatch',
            name='service_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedrepair',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='completedservice',
            name='service_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repairreadytodispatch',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startedrepair',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startedservice',
            name='service_description',
            field=models.TextField(),
        ),
    ]
