# Generated by Django 5.0.1 on 2024-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0080_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
