# Generated by Django 5.0.1 on 2024-02-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0081_alter_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedwarranty',
            name='accepted_datetime',
        ),
        migrations.RemoveField(
            model_name='rejectedwarranty',
            name='accepted_datetime',
        ),
        migrations.DeleteModel(
            name='AcceptedWarrantyApplication',
        ),
    ]
