# Generated by Django 5.0.1 on 2024-02-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0082_remove_finishedwarranty_accepted_datetime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartedService',
            new_name='AcceptedService',
        ),
        migrations.DeleteModel(
            name='ServiceReadyToDispatch',
        ),
    ]
