# Generated by Django 5.0.1 on 2024-02-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0083_rename_startedservice_acceptedservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedservice',
            old_name='started_datetime',
            new_name='accepted_datetime',
        ),
    ]
