# Generated by Django 5.0.1 on 2024-02-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0084_rename_started_datetime_acceptedservice_accepted_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedservice',
            old_name='started_datetime',
            new_name='accepted_datetime',
        ),
    ]
