# Generated by Django 5.0.1 on 2024-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0085_rename_started_datetime_completedservice_accepted_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedservice',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
