# Generated by Django 5.0.1 on 2024-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0086_acceptedservice_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedservice',
            name='application_datetime',
            field=models.DateTimeField(),
        ),
    ]
