# Generated by Django 5.0.1 on 2024-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0087_alter_completedservice_application_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedservice',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
