# Generated by Django 5.0.1 on 2024-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0088_completedservice_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedservice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='completed service files/'),
        ),
    ]
