# Generated by Django 5.0.1 on 2024-03-05 15:48

import django.db.models.deletion
import ipcs_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0092_remove_rejectedwarranty_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedWarranty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('application_datetime', models.DateTimeField()),
                ('finished_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('product_complain', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedWarranty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('application_datetime', models.DateTimeField()),
                ('rejected_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('product_complain', models.TextField()),
                ('reason', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyApplication',
            fields=[
                ('id', models.CharField(default=ipcs_admin.models.warranty_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('application_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('product_complain', models.TextField()),
                ('address', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcs_admin.product')),
            ],
        ),
    ]
