# Generated by Django 5.0.1 on 2024-03-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0093_finishedwarranty_rejectedwarranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedwarranty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipcs_admin.product'),
        ),
        migrations.AlterField(
            model_name='rejectedwarranty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipcs_admin.product'),
        ),
        migrations.AlterField(
            model_name='warrantyapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipcs_admin.product'),
        ),
    ]
