# Generated by Django 5.0.1 on 2024-03-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0094_alter_finishedwarranty_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptedService',
        ),
        migrations.DeleteModel(
            name='CompletedRepair',
        ),
        migrations.DeleteModel(
            name='CompletedService',
        ),
        migrations.DeleteModel(
            name='RepairReadyToDispatch',
        ),
        migrations.DeleteModel(
            name='RepairRequest',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.DeleteModel(
            name='StartedRepair',
        ),
    ]
