# Generated by Django 5.0.1 on 2024-04-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0096_acceptedservice_completedrepair_completedservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminotp',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
