# Generated by Django 5.0.1 on 2024-04-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcs_admin', '0098_alter_adminotp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminotp',
            old_name='name',
            new_name='email',
        ),
    ]
